defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

[acme]
caServer = "https://acme-staging.api.letsencrypt.org/directory"
email = "andrewsav@domain.tld"
storage = "/etc/traefik/acme/acme.json"
entryPoint = "https"

[[acme.domains]]
  main = "domain.tld"

[docker]
endpoint = "unix:///var/run/docker.sock"
exposedbydefault = false
